# Generated by Django 6.0.7 on 2026-07-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('location', models.CharField(choices=[('alleppey', 'Alleppey (Alappuzha) - Backwaters'), ('munnar', 'Munnar - Tea Estates & Misty Hills'), ('varkala', 'Varkala - Cliffside Oceanfront'), ('fort_kochi', 'Fort Kochi - Heritage & Culture'), ('wayanad', 'Wayanad - Rainforest & Sanctuary'), ('kumarakom', 'Kumarakom - Lake & Lagoon')], max_length=50)),
                ('location_display_name', models.CharField(default='Kerala', max_length=100)),
                ('property_type', models.CharField(choices=[('villa', 'Luxury Private Villa'), ('houseboat', 'Heritage Houseboat'), ('estate', 'Plantation Estate Manor'), ('bungalow', 'Colonial Heritage Bungalow'), ('cottage', 'Cliffside Ocean Cottage')], max_length=50)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField(default=2)),
                ('bathrooms', models.PositiveIntegerField(default=2)),
                ('max_guests', models.PositiveIntegerField(default=4)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('main_image', models.URLField(max_length=500)),
                ('gallery_json', models.JSONField(blank=True, default=list)),
                ('amenities_json', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(default=4.9)),
                ('reviews_count', models.PositiveIntegerField(default=18)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-is_featured', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('guests', models.PositiveIntegerField(default=2)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='rentals.property')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
