# Generated by Django 6.0.7 on 2026-08-16 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_seed_4_nopool_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('alleppey', 'Alleppey (Alappuzha) - Backwaters'), ('munnar', 'Munnar - Tea Estates & Misty Hills'), ('varkala', 'Varkala - Cliffside Oceanfront'), ('fort_kochi', 'Fort Kochi - Heritage & Culture'), ('wayanad', 'Wayanad - Rainforest & Sanctuary'), ('kumarakom', 'Kumarakom - Lake & Lagoon'), ('vagamon', 'Vagamon - Misty Pine Valleys'), ('kovalam', 'Kovalam - Gold Sand Coastal Reserve'), ('athirappilly', 'Athirappilly - Rainforest & Waterfalls'), ('thekkady', 'Thekkady - Spice Plantation Sanctuary'), ('idukki', 'Idukki - High Range Valleys'), ('kannur', 'Kannur - Malabar Coast Cliffs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('villa', 'Luxury Private Villa'), ('houseboat', 'Heritage Houseboat'), ('estate', 'Plantation Estate Manor'), ('bungalow', 'Colonial Heritage Bungalow'), ('cottage', 'Cliffside Ocean Cottage'), ('residence', 'Modern High-End Residence')], max_length=50),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Email Verification Tokens',
            },
        ),
    ]
