# Generated by Django 6.0.7 on 2026-08-16 15:21

import rentals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_property_location_alter_property_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(default=rentals.models.generate_token_str, max_length=64, unique=True),
        ),
    ]
