# Generated by Django 6.0.7 on 2026-09-04 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_emailverificationtoken_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('preferred_location', models.CharField(blank=True, choices=[('alleppey', 'Alleppey (Alappuzha) - Backwaters'), ('munnar', 'Munnar - Tea Estates & Misty Hills'), ('varkala', 'Varkala - Cliffside Oceanfront'), ('fort_kochi', 'Fort Kochi - Heritage & Culture'), ('wayanad', 'Wayanad - Rainforest & Sanctuary'), ('kumarakom', 'Kumarakom - Lake & Lagoon'), ('vagamon', 'Vagamon - Misty Pine Valleys'), ('kovalam', 'Kovalam - Gold Sand Coastal Reserve'), ('athirappilly', 'Athirappilly - Rainforest & Waterfalls'), ('thekkady', 'Thekkady - Spice Plantation Sanctuary'), ('idukki', 'Idukki - High Range Valleys'), ('kannur', 'Kannur - Malabar Coast Cliffs')], default='alleppey', max_length=50)),
                ('bio', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
