# Generated by Django 6.0.7 on 2026-09-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_ensure_unique_property_galleries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.CharField(max_length=500),
        ),
    ]
